import type { Dispatch, SetStateAction } from "react";
import type { CompareResult, GapDiagnostics, GapRow, Persona, WorkflowItem, XmlValidationState } from "../types";

export type AuditLevel = "info" | "success" | "warn";
export type ChatMessage = { id: number; role: "user" | "assistant"; text: string; at: string };

export type UseWorkbenchActionsArgs = {
  persona: Persona | "";
  projectId: string;
  currentWorkflow: WorkflowItem | null;
  activeWorkflowId: number | null;
  workflowName: string;
  workflowPsdVersion: string;
  workflowComment: string;
  sendBackReasonCode: string;
  sendBackReasonDetail: string;
  baUserContext: string;
  baModel: string;
  devUserContext: string;
  devModel: string;
  revUserContext: string;
  revModel: string;
  chatInput: string;
  chatIncludeAll: boolean;
  chatModel: string;
  fcaArtifactId: number | "";
  modelArtifactId: number | "";
  dataArtifactId: number | "";
  reportXmlArtifactId: number | "";
  xsdArtifactId: number | "";
  compareBaselineId: number | "";
  compareChangedId: number | "";
  gapRunId: number | null;
  gapDiagnostics: GapDiagnostics | null;
  remediationStatuses: string[];
  remediationArtifactIds: number[];
  remediationUserContext: string;
  setBackendUp: Dispatch<SetStateAction<boolean | null>>;
  setBackendStatusText: Dispatch<SetStateAction<string>>;
  setLlmUp: Dispatch<SetStateAction<boolean | null>>;
  setArtifacts: Dispatch<SetStateAction<any[]>>;
  setWorkflows: Dispatch<SetStateAction<WorkflowItem[]>>;
  setWorkflowName: Dispatch<SetStateAction<string>>;
  setWorkflowPsdVersion: Dispatch<SetStateAction<string>>;
  setWorkflowNameError: Dispatch<SetStateAction<string>>;
  setWorkflowComment: Dispatch<SetStateAction<string>>;
  setWorkflowBusy: Dispatch<SetStateAction<boolean>>;
  setBusy: Dispatch<SetStateAction<boolean>>;
  setMessage: Dispatch<SetStateAction<string>>;
  setFcaArtifactId: Dispatch<SetStateAction<number | "">>;
  setModelArtifactId: Dispatch<SetStateAction<number | "">>;
  setDataArtifactId: Dispatch<SetStateAction<number | "">>;
  setXsdArtifactId: Dispatch<SetStateAction<number | "">>;
  setSendBackReasonCode: Dispatch<SetStateAction<string>>;
  setSendBackReasonDetail: Dispatch<SetStateAction<string>>;
  setGapRunId: Dispatch<SetStateAction<number | null>>;
  setGapRows: Dispatch<SetStateAction<GapRow[]>>;
  setGapDiagnostics: Dispatch<SetStateAction<GapDiagnostics | null>>;
  setSqlRunId: Dispatch<SetStateAction<number | null>>;
  setSqlScript: Dispatch<SetStateAction<string>>;
  setXmlRunId: Dispatch<SetStateAction<number | null>>;
  setXmlValidation: Dispatch<SetStateAction<XmlValidationState | null>>;
  setCompareResult: Dispatch<SetStateAction<CompareResult | null>>;
  setCompareBusy: Dispatch<SetStateAction<boolean>>;
  setReportXmlLinked: Dispatch<SetStateAction<boolean>>;
  setReportXmlPreview: Dispatch<SetStateAction<string>>;
  setReportXmlArtifactId: Dispatch<SetStateAction<number | "">>;
  setRemediationStatuses: Dispatch<SetStateAction<string[]>>;
  setRemediationArtifactIds: Dispatch<SetStateAction<number[]>>;
  setRemediationUserContext: Dispatch<SetStateAction<string>>;
  setActiveWorkflowId: Dispatch<SetStateAction<number | null>>;
  setActiveAgentTab: Dispatch<SetStateAction<"ba" | "dev" | "rev">>;
  setChatInput: Dispatch<SetStateAction<string>>;
  setChatBusy: Dispatch<SetStateAction<boolean>>;
  setChatResponse: Dispatch<SetStateAction<string>>;
  setChatHistory: Dispatch<SetStateAction<ChatMessage[]>>;
  addToast: (kind: "success" | "error", text: string) => void;
  pushAudit: (level: AuditLevel, text: string) => void;
};
